In [116]:
import pandas as pd
import numpy as np

In [ ]:
# Relative or exact path file
# data = pd.read_csv("/home/pankaj/Downloads/Online_food_ordering/online food delivery dataset.csv")
# print(data)

In [7]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("srisyra02/online-food-ordering-dataset")

print("Path to dataset files:", path)

/home/pankaj/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /home/pankaj/.cache/kagglehub/datasets/srisyra02/online-food-ordering-dataset/versions/1

In [8]:
import os
print("os.listdir(path):", os.listdir(path))

os.listdir(path): ['online food delivery dataset.csv']

In [9]:
df = pd.read_csv(os.path.join(path, "online food delivery dataset.csv"))
df.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,Yes

In [10]:
df.head(5)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,Yes

In [11]:
df.shape

(388, 14)

In [12]:
df.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'Customer Type',
       'latitude', 'longitude', 'Pin code', 'Output', 'Feedback',
       'Unnamed: 13'],
      dtype='object')

In [13]:
df.dtypes

Age                             int64
Gender                         object
Marital Status                 object
Occupation                     object
Monthly Income                 object
Educational Qualifications     object
Family size                     int64
Customer Type                  object
latitude                      float64
longitude                     float64
Pin code                        int64
Output                         object
Feedback                       object
Unnamed: 13                    object
dtype: object

In [14]:
average_age = df['Age'].mean()
print(average_age)

24.628865979381445

In [15]:
minimum_age = df['Age'].min()
print(minimum_age)

18

In [16]:
maximum_age = df['Age'].max()
print(maximum_age)

33

In [17]:
number_of_male = df[df["Gender"] == "Male"]
print(number_of_male)

     Age Gender     Marital Status Occupation  Monthly Income  \
2     22   Male             Single    Student  Below Rs.10000
4     22   Male             Single    Student  Below Rs.10000
6     22   Male             Single    Student       No Income
11    23   Male             Single    Student  Below Rs.10000
12    23   Male             Single    Student       No Income
..   ...    ...                ...        ...             ...
377   31   Male  Prefer not to say   Employee  Below Rs.10000
379   22   Male             Single    Student  Below Rs.10000
381   22   Male             Single    Student       No Income
386   23   Male             Single    Student  Below Rs.10000
387   23   Male             Single    Student       No Income

    Educational Qualifications  Family size Customer Type  latitude  \
2                Post Graduate            3       Regular   12.9551
4                Post Graduate            4      Frequent   12.9850
6                     Graduate            3       Regular   12.9770
11               Post Graduate            2       Regular   12.9770
12               Post Graduate            5      Frequent   12.8988
..                         ...          ...           ...       ...
377                   Graduate            1           New   12.9866
379              Post Graduate            4      Frequent   12.9850
381                   Graduate            3       Regular   12.9770
386              Post Graduate            2       Regular   12.9770
387              Post Graduate            5      Frequent   12.8988

     longitude  Pin code Output   Feedback Unnamed: 13
2      77.6593    560017    Yes  Negative          Yes
4      77.5533    560010    Yes   Positive         Yes
6      77.5773    560009    Yes   Positive         Yes
11     77.5773    560009    Yes  Negative          Yes
12     77.5764    560078    Yes   Positive         Yes
..         ...       ...    ...        ...         ...
377    77.4904    560091     No  Negative           No
379    77.5533    560010    Yes   Positive         Yes
381    77.5773    560009    Yes   Positive         Yes
386    77.5773    560009    Yes   Positive         Yes
387    77.5764    560078    Yes   Positive         Yes

[222 rows x 14 columns]

In [18]:
number_of_female = df[df["Gender"] == "Female"].shape[0]
print(number_of_female)

166

In [19]:
df["Age"] > 25

0      False
1      False
2      False
3      False
4      False
       ...
383    False
384    False
385    False
386    False
387    False
Name: Age, Length: 388, dtype: bool

In [20]:
df["Occupation"] == "Employee"

0      False
1      False
2      False
3      False
4      False
       ...
383    False
384    False
385    False
386    False
387    False
Name: Occupation, Length: 388, dtype: bool

In [21]:
df[["Age", "Gender", "Occupation", "Monthly Income"]]

     Age  Gender Occupation  Monthly Income
0     20  Female    Student       No Income
1     24  Female    Student  Below Rs.10000
2     22    Male    Student  Below Rs.10000
3     22  Female    Student       No Income
4     22    Male    Student  Below Rs.10000
..   ...     ...        ...             ...
383   23  Female    Student       No Income
384   23  Female    Student       No Income
385   22  Female    Student       No Income
386   23    Male    Student  Below Rs.10000
387   23    Male    Student       No Income

[388 rows x 4 columns]

In [22]:
average_age = df.groupby("Occupation")["Age"].mean()
print(average_age)
highest_age_occupation = average_age.idxmax()
print(highest_age_occupation)
print(average_age[highest_age_occupation])

Occupation
Employee          26.576271
House wife        30.333333
Self Employeed    26.388889
Student           22.811594
Name: Age, dtype: float64
House wife
30.333333333333332

In [23]:
feedback = df["Feedback"].value_counts()

In [24]:
df.Feedback

0       Positive
1       Positive
2      Negative
3       Positive
4       Positive
         ...
383     Positive
384     Positive
385     Positive
386     Positive
387     Positive
Name: Feedback, Length: 388, dtype: object

In [25]:
feedback_count = df["Feedback"].value_counts()

print(feedback_count)

positive_count = (df["Feedback"] == "Positive").sum()

total_customers = len(df)

print(positive_count)

positive_percentage = (positive_count / total_customers) * 100

print(positive_percentage)

Feedback
Positive     317
Negative      71
Name: count, dtype: int64
Positive customers: 317
Positive feedback percentage: 81.70103092783505

In [26]:
df["Feedback"] == "Positive"

0       True
1       True
2      False
3       True
4       True
       ...
383     True
384     True
385     True
386     True
387     True
Name: Feedback, Length: 388, dtype: bool

In [31]:
df.groupby(["Occupation", "Feedback"]).size().reset_index(name="Customer Count")
#Size()-Counts the number of customers in each group.

       Occupation   Feedback  Customer Count
0        Employee  Negative               33
1        Employee   Positive              85
2      House wife  Negative                1
3      House wife   Positive               8
4  Self Employeed  Negative               16
5  Self Employeed   Positive              38
6         Student  Negative               21
7         Student   Positive             186

In [69]:
class BankAccount:
    def __init__(self, account_num, owner, balance):
        self.account_num = account_num
        self.owner = owner
        self.balance = balance
    
    def deposit(self, amount):
        self.balance += amount
        print("Deposited:", amount)

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
        #     print("Withdrawn:", amount)
        # else:
        #     print("Insufficient balance")
            return True
        else:
            return False
            
    def display(self):
        print("Account Number:", self.account_num)
        print("Owner:", self.owner)
        print("Balance:", self.balance)
        
    def __str__(self):
        return (
            f"Account Number: {self.account_num}\n"
            f"Owner: {self.owner}\n"
            f"Balance: {self.balance}"
        )

account1 = BankAccount("101", "Pankaj", 1000)
account2 = BankAccount("102", "John", 2000)

print(account1.account_num, account1.owner, account1.balance)
print(account2.account_num, account2.owner, account2.balance)

101 Pankaj 1000
102 John 2000

In [60]:
account1.deposit(500)
account1.display()
account1.withdraw(200)
account1.display()
account1.withdraw(3000)

Deposited: 500
Account Number: 101
Owner: Pankaj
Balance: 1500
Account Number: 101
Owner: Pankaj
Balance: 1300

False

In [61]:
result = account1.withdraw(150)

print(f"Withdrawal Status: {result}")
print(f"Account Balance: {account1.balance}")

Withdrawal Status: True
Account Balance: 1150

In [62]:
result = account1.withdraw(5000)

print(f"Withdrawal Status: {result}")
print(f"Account Balance: {account1.balance}")

Withdrawal Status: False
Account Balance: 1150

In [63]:
print(account1)

Account Number: 101
Owner: Pankaj
Balance: 1150

In [70]:
print(account1.__str__())

Account Number: 101
Owner: Pankaj
Balance: 1000

In [72]:
class Student:
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks
        
        # average_marks
    def average_marks(self):
        return sum(self.marks) / len(self.marks)

In [73]:
Student1 = Student("Alice", 101, [85, 90, 78])
Student2 = Student("Bob", 102, [75, 80, 88])
Student3 = Student("Rahul", 103, [92, 88, 95])

In [74]:
print(f"{Student1.name} (Roll No: {Student1.roll_no}) - Average Marks: {Student1.average_marks()}")
print(f"{Student2.name} (Roll No: {Student2.roll_no}) - Average Marks: {Student2.average_marks()}")
print(f"{Student3.name} (Roll No: {Student3.roll_no}) - Average Marks: {Student3.average_marks()}")

Alice (Roll No: 101) - Average Marks: 84.33333333333333
Bob (Roll No: 102) - Average Marks: 81.0
Rahul (Roll No: 103) - Average Marks: 91.66666666666667

In [100]:
class Vehicle:
    def __init__(self, brand):
        self.brand = brand
        
    def move(self):
        print("Vehicle is moving")


class Car(Vehicle):
    def __init__(self, brand, doors):
        super().__init__(brand)
        self.doors = doors
    
    def move(self):
        print("Car is driving on the road")


class Boat(Vehicle):
    def move(self):
        print("Boat is sailing on water")

In [97]:
vehicle = Vehicle()
car = Car()
boat = Boat()

In [98]:

vehicle.move()
car.move()
boat.move()

Vehicle is moving
Car is driving on the road
Boat is sailing on water

In [108]:
car1 = Car("Toyota", 4)
car2 = Car("BMW", 2)

In [109]:
print("Car 1:")
print("Brand:", car1.brand)
print("Doors:", car1.doors)

Car 1:
Brand: Toyota
Doors: 4

In [106]:
print("Car 2:")
print("Brand:", car2.brand)
print("Doors:", car2.doors)

Car 2:
Brand: BMW
Doors: 2

In [ ]:
class Car:
    def move(self):
        print("Car is driving on the road")


class Boat:
    def move(self):
        print("Boat is sailing on water")


class Airplane:
    def move(self):
        print("Airplane is flying in the sky")

Car is driving on the road
Boat is sailing on water
Airplane is flying in the sky

In [114]:

car = Car()
boat = Boat()
airplane = Airplane()

vehicles = [car, boat, airplane]

In [115]:
for vehicle in vehicles:
    vehicle.move()

Car is driving on the road
Boat is sailing on water
Airplane is flying in the sky